server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}
  servlet:
    context-path: /digitalizacion
spring:
  config:
    import: optional:file:.env[.properties]
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#        schema_update:
#          unique_constraint_strategy: RECREATE_QUIETLY
#    database: POSTGRESQL
#    show-sql: true
#    open-in-view: false
  datasource:
    digitalizacion:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${DB_HOST}/${DB_SCHEMA}
      username: ${USERNAME}
      password: ${PASSWORD}
      hibernate-hbm2ddl-auto: update
    soa:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_TAM}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    compusoft:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_COMPUSOFT}:${DB_PORT_COMPUSOFT}:${DB_SCHEMA_COMPUSOFT}
      username: ${USERNAME_COMPUSOFT}
      password: ${PASSWORD_COMPUSOFT}
      hibernate-hbm2ddl-auto: none
      