server:
  port: 8080
  servlet:
    context-path: /digitalizacion
spring:
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#        schema_update:
#          unique_constraint_strategy: RECREATE_QUIETLY
#    database: POSTGRESQL
#    show-sql: true
#    open-in-view: false
  datasource:
    digitalizacion:
      driver-class-name: org.${USERNAME}ql.Driver
      jdbc-url: jdbc:${USERNAME}ql://${DB_HOST}/digitalizacion
      username: ${USERNAME}
      password: ${PASSWORD}
      hibernate-hbm2ddl-auto: update
    soa:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_TAM}:1521:XE
      username: SOA
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    compusoft:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_TAM}:1521:XE
      username: COMPUSOFT
      password: ${PASSWORD_COMPUSOFT}
      hibernate-hbm2ddl-auto: none
      